apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ew3r
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0032-tenant/tkrw-pr712-0075-0032-app/devfile-sample-ew3r@sha256:07390d58a51ff68afe49ced6cbcce207ff0c98f5c2595bc54a4fe27dec61d352
        name: my-nodejs
        resources: {}
status: {}
